"""
Smoke test for note generation plumbing without a real network call.

Run:
    python tests/test_note_builder.py
"""

from __future__ import annotations

import json
import shutil
import sys
from pathlib import Path
from unittest.mock import patch

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.book_pipeline import run_book_pipeline
from src.chat import create_book_sessions
from src.note_builder import generate_notes


def fake_call(provider_config, messages, timeout=180):
    user = messages[-1]["content"]
    if "全书总览" in user:
        return "# 全书总览\n\n这是中文全书总览。"
    return (
        "# 重构讲解\n\n"
        "## 概念\n这是中文概念讲解。\n\n"
        "## 模块与关系\n说明本章模块和前后篇章关系。\n\n"
        "## 知识重点\n列出学习重点。"
    )


def main() -> int:
    pdf = ROOT / "book" / "introductiontocomputermusic.pdf"
    out = ROOT / "tmp_note_builder"
    if out.exists():
        shutil.rmtree(out)
    out.mkdir()

    result = run_book_pipeline(pdf, out)
    book_json = Path(result["book_json_path"])
    book = json.loads(book_json.read_text(encoding="utf-8"))
    book["chapters"] = book["chapters"][:2]
    book_json.write_text(json.dumps(book, ensure_ascii=False, indent=2), encoding="utf-8")

    provider = {"base_url": "https://example.test/v1", "api_key": "test", "model": "fake"}
    with patch("src.note_builder._call_chat", fake_call):
        stats = generate_notes(book_json, provider, "中文", "请生成章节笔记", distill_percent=50)

    book = json.loads(book_json.read_text(encoding="utf-8"))
    session_ids = create_book_sessions(book_json, provider)
    first_note = Path(book["chapters"][0]["note_path"]).read_text(encoding="utf-8")

    checks = [
        ("chapter notes generated by percent", stats["generated"] == 2),
        ("chapter note path saved", Path(book["chapters"][0]["note_path"]).is_file()),
        ("overview path saved", Path(book["memory"]["overview_path"]).is_file()),
        ("note is Chinese reconstruction", "重构讲解" in first_note and "原文预览" not in first_note),
        ("sessions include two chapters and overview", len(session_ids) == 3),
    ]
    failed = [name for name, ok in checks if not ok]
    for name, ok in checks:
        print(f"{'PASS' if ok else 'FAIL'}: {name}")
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
